#! /usr/bin/env python3

import sys
import re

FILE_HEADER = '''#pragma once
//This File is autogenerated an may be overridden, do not change
//If you need to change the content of the file please change the file
//sources/message_hdr.py'''

prefix = sys.argv[1] + '/'

def remove_prefix(text, prefix):
  return re.sub(r'^{0}'.format(re.escape(prefix)), '', text)


if __name__ == "__main__":
    with open(sys.argv[2], 'w') as output:
        output.write(f"{FILE_HEADER}\n")
        for i in range(3, len(sys.argv)):
            for include in sys.argv[i].split(';'):
                include = remove_prefix(include, prefix)
                output.write(f"#include <{include}>\n")
