# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: txn_format.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10txn_format.proto\x12\x07TxnTest\"A\n\x06KVPair\x12\x1b\n\x02op\x18\x01 \x01(\x0e\x32\x0f.TxnTest.OpType\x12\x0b\n\x03key\x18\x02 \x01(\x0c\x12\r\n\x05value\x18\x03 \x01(\x0c\"X\n\x03Txn\x12\x0e\n\x06txn_id\x18\x01 \x01(\x04\x12\x12\n\ndepends_on\x18\x02 \x03(\x04\x12\x1d\n\x04\x63mds\x18\x03 \x03(\x0b\x32\x0f.TxnTest.KVPair\x12\x0e\n\x06is_txn\x18\x04 \x01(\x08\"\"\n\x04Test\x12\x1a\n\x04txns\x18\x01 \x03(\x0b\x32\x0c.TxnTest.Txn*\xca\x01\n\x06OpType\x12\n\n\x06OP_PUT\x10\x00\x12\n\n\x06OP_GET\x10\x01\x12\x17\n\x13OP_SEND_AND_EXECUTE\x10\x02\x12\n\n\x06OP_SET\x10\x03\x12\n\n\x06OP_ADD\x10\x04\x12\n\n\x06OP_SUB\x10\x05\x12\x0b\n\x07OP_MULT\x10\x06\x12\n\n\x06OP_DIV\x10\x07\x12\n\n\x06OP_MOD\x10\x08\x12\n\n\x06OP_AND\x10\t\x12\t\n\x05OP_OR\x10\n\x12\n\n\x06OP_XOR\x10\x0b\x12\n\n\x06OP_NOT\x10\x0c\x12\x0b\n\x07OP_NAND\x10\r\x12\n\n\x06OP_NOR\x10\x0e\x62\x06proto3')

_OPTYPE = DESCRIPTOR.enum_types_by_name['OpType']
OpType = enum_type_wrapper.EnumTypeWrapper(_OPTYPE)
OP_PUT = 0
OP_GET = 1
OP_SEND_AND_EXECUTE = 2
OP_SET = 3
OP_ADD = 4
OP_SUB = 5
OP_MULT = 6
OP_DIV = 7
OP_MOD = 8
OP_AND = 9
OP_OR = 10
OP_XOR = 11
OP_NOT = 12
OP_NAND = 13
OP_NOR = 14


_KVPAIR = DESCRIPTOR.message_types_by_name['KVPair']
_TXN = DESCRIPTOR.message_types_by_name['Txn']
_TEST = DESCRIPTOR.message_types_by_name['Test']
KVPair = _reflection.GeneratedProtocolMessageType('KVPair', (_message.Message,), {
  'DESCRIPTOR' : _KVPAIR,
  '__module__' : 'txn_format_pb2'
  # @@protoc_insertion_point(class_scope:TxnTest.KVPair)
  })
_sym_db.RegisterMessage(KVPair)

Txn = _reflection.GeneratedProtocolMessageType('Txn', (_message.Message,), {
  'DESCRIPTOR' : _TXN,
  '__module__' : 'txn_format_pb2'
  # @@protoc_insertion_point(class_scope:TxnTest.Txn)
  })
_sym_db.RegisterMessage(Txn)

Test = _reflection.GeneratedProtocolMessageType('Test', (_message.Message,), {
  'DESCRIPTOR' : _TEST,
  '__module__' : 'txn_format_pb2'
  # @@protoc_insertion_point(class_scope:TxnTest.Test)
  })
_sym_db.RegisterMessage(Test)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OPTYPE._serialized_start=223
  _OPTYPE._serialized_end=425
  _KVPAIR._serialized_start=29
  _KVPAIR._serialized_end=94
  _TXN._serialized_start=96
  _TXN._serialized_end=184
  _TEST._serialized_start=186
  _TEST._serialized_end=220
# @@protoc_insertion_point(module_scope)
